[package]
name = "wasmer/edgejs-quickjs"
version = "0.0.5"
description = "Edge.js with an embedded QuickJS N-API provider"
entrypoint = "edge"

[[module]]
name = "edge"
source = "../build-quickjs-wasix/edgejs.wasm"
abi = "wasi"

[[command]]
name = "edge"
module = "edge"

[fs]
"/etc" = "./etc"
"/usr/local/ssl" = "../ssl-certs"

[dependencies]
"wasmer/bash" = "1.0.25"